services:
  - type: web
    name: rooftop-ticketbot
    env: python
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: PANEL_PASSWORD
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: PORT
        value: 10000
